const ACTIONS = {
  UPDATE_BUILDINGS: "UPDATE_BUILDINGS",
  UPDATE_ROOMS_AND_MEETINGS: "UPDATE_ROOMS_AND_MEETINGS",
  UPDATE_BOOKING_DATA: "UPDATE_BOOKING_DATA",
  BOOK_ROOM: "BOOK_ROOM",
};
export default ACTIONS;
